"""Guided four-stage exercises: recognize, verify, act and follow up."""
from .chat_sources import PRIVACY, LAW, PRODHAB, OIJ

def step(title, scene, question, alternatives, correct, explanations, consequence):
    return dict(title=title, scene=scene, question=question,
                options=[f'{letter}) {value}' for letter, value in zip('ABC', alternatives)],
                correct=correct, explanations=explanations, consequence=consequence)

SIMULATIONS = {
    'bank': dict(label='Mensaje de tu banco', goal='Verificar un aviso sin exponer tu cuenta.', sources=[PRIVACY], steps=[
        step('Reconocer señales', 'Recibes un mensaje: «Tu cuenta se bloqueará en 15 minutos. Entra en este enlace y confirma el código». Tiene el logotipo del banco.', '¿Qué te hace detenerte?', ['La urgencia y la solicitud del código', 'El logotipo demuestra que es auténtico', 'Que el mensaje llegó de día'], 'A', ['La presión y la solicitud de un código son señales para verificar.', 'Los logotipos se pueden copiar; no demuestran quién envió el mensaje.', 'La hora de llegada no permite saber si es legítimo.'], 'No se ha confirmado un fraude. Puedes verificar sin seguir el enlace.'),
        step('Verificar por otra vía', 'Necesitas saber si el aviso corresponde a tu banco.', '¿Qué canal eliges?', ['El teléfono incluido en el mensaje', 'La aplicación oficial que ya utilizas', 'Responder al remitente'], 'B', ['Ese número puede pertenecer al mismo remitente. Busca el contacto por tu cuenta.', 'Un canal oficial independiente permite comprobar el aviso sin usar el enlace.', 'El remitente no es una fuente independiente para comprobar su propia identidad.'], 'En la aplicación no aparece ese aviso. El mensaje sigue sin verificarse.'),
        step('Responder a una exposición', 'En esta nueva etapa, imagina que antes de detenerte escribiste tu contraseña en el enlace. No compartiste ningún código.', '¿Qué haces primero?', ['Esperar a que aparezca un cargo', 'Borrar el mensaje y seguir usando la cuenta', 'Contactar al banco por su canal oficial y proteger el acceso'], 'C', ['Esperar puede prolongar la exposición. Actúa por un canal oficial.', 'Borrar el mensaje no protege una contraseña que ya compartiste.', 'Explica lo ocurrido al banco y sigue sus medidas para proteger el acceso.'], 'No necesitas confirmar una pérdida para informar de credenciales expuestas.'),
        step('Dar seguimiento', 'Ya contactaste al banco por un canal oficial y protegiste el acceso.', '¿Cómo sigues?', ['Guardar el mensaje, revisar movimientos y no compartir códigos', 'Publicar capturas con todos los datos de la cuenta', 'Asumir que cambiar la contraseña elimina todo riesgo'], 'A', ['Conservar evidencia y revisar movimientos ayuda al seguimiento.', 'Publicar datos de la cuenta crea otra exposición. Conserva la evidencia de forma privada.', 'Cambiar el acceso es una medida; también conviene revisar actividad y seguir las indicaciones del banco.'], 'Si detectas movimientos no reconocidos, comunícalos al banco por su canal oficial.'),
    ]),
    'social': dict(label='Publicación en redes sociales', goal='Decidir qué publicar y reducir una exposición.', sources=[PRIVACY], steps=[
        step('Reconocer lo que expones', 'Quieres publicar una foto de una matrícula. Se ven tu identificación, domicilio y un código de acceso.', '¿Qué revisas antes de publicarla?', ['Solo si la foto se ve bien', 'Los datos y códigos que otras personas podrían usar', 'Cuántos seguidores tengo'], 'B', ['La calidad de la imagen no determina si revela información.', 'Revisa la información visible antes de decidir la audiencia.', 'Pocos seguidores no impiden capturas o reenvíos.'], 'Puedes compartir la noticia sin mostrar documentos ni códigos.'),
        step('Elegir una publicación segura', 'Quieres contar que te matriculaste sin divulgar el documento.', '¿Qué alternativa eliges?', ['Publicar el documento en un perfil privado', 'Dejar visible solo el código de acceso', 'Publicar un texto sin el documento'], 'C', ['Un perfil privado reduce audiencia, pero no controla todas las copias.', 'Un código puede permitir acciones o acceso; también debe protegerse.', 'Puedes compartir la noticia sin exponer información del documento.'], 'La audiencia también importa, incluso si decides no incluir el documento.'),
        step('Actuar si ya se publicó', 'Para practicar la respuesta, imagina que la foto original estuvo visible y alguien la compartió.', '¿Qué medida tiene más sentido?', ['Retirar la publicación y solicitar que eliminen las copias', 'Cambiarla a privada y dar el problema por resuelto', 'Volver a publicarla para advertir a todos'], 'A', ['Reduce la exposición y solicita retirar las copias mediante los canales disponibles.', 'Cambiar la audiencia no elimina las copias existentes.', 'Repetir la publicación vuelve a exponer los datos.'], 'No puedes garantizar que desaparezcan todas las copias. Revisa también si debes reemplazar el código expuesto.'),
        step('Prevenir una nueva exposición', 'Quieres conservar el hábito de compartir noticias personales.', '¿Qué rutina adoptas?', ['Confiar en que mis contactos nunca reenvían', 'Revisar datos, audiencia y ubicación antes de publicar', 'Publicar y corregir solo si alguien se queja'], 'B', ['La confianza no permite controlar todas las copias.', 'Una revisión breve antes de publicar reduce exposiciones evitables.', 'La revisión previa evita depender de una advertencia posterior.'], 'Comparte solo lo necesario para contar la noticia.'),
    ]),
    'app': dict(label='Permisos de una aplicación', goal='Relacionar permisos con su finalidad y revisar accesos.', sources=[PRIVACY], steps=[
        step('Reconocer un permiso excesivo', 'Una aplicación de linterna pide contactos y ubicación permanente.', '¿Qué revisas?', ['La relación entre esos permisos y la función de linterna', 'Solo las estrellas de la tienda', 'Si aceptar todos los permisos acelera la instalación'], 'A', ['Un permiso debe tener una finalidad comprensible relacionada con el uso.', 'Las valoraciones no explican por qué se necesitan esos accesos.', 'La rapidez no compensa aceptar accesos que no comprendes.'], 'La solicitud exige una revisión; por sí sola no demuestra que la aplicación sea maliciosa.'),
        step('Tomar una decisión informada', 'La aplicación no explica para qué necesita contactos.', '¿Cómo continúas?', ['Aceptar para poder probarla', 'Revisar el origen, la información de privacidad y buscar una alternativa', 'Confiar porque es gratuita'], 'B', ['Probarla con accesos innecesarios ya puede exponer información.', 'Comprueba el origen y las condiciones; puedes elegir otra aplicación.', 'El precio no demuestra una finalidad adecuada.'], 'Puedes rechazar el permiso o no instalarla si no entiendes su necesidad.'),
        step('Revisar accesos concedidos', 'En esta etapa imagina que la instalaste y concediste los permisos.', '¿Qué haces?', ['Ocultar el icono', 'Cerrar la aplicación una vez', 'Revisar y revocar permisos; desinstalar si no la necesitas'], 'C', ['Ocultar el icono no elimina permisos.', 'Cerrar la aplicación no equivale a revocar accesos.', 'Revisa los permisos en el dispositivo y retira los accesos innecesarios.'], 'Revocar permisos evita accesos futuros según el sistema; no garantiza borrar datos ya enviados.'),
        step('Revisar datos ya recopilados', 'La información de privacidad indica que se pudieron recopilar datos.', '¿Qué paso eliges?', ['Consultar al responsable sobre el tratamiento y conservar la gestión', 'Suponer que desinstalar borró todo en el servidor', 'Enviar mi contraseña para que identifiquen la cuenta'], 'A', ['Consulta finalidad, datos y canales para ejercer tus derechos.', 'La eliminación local no demuestra la eliminación en sistemas externos.', 'No envíes tu contraseña; usa el procedimiento oficial de la entidad.'], 'Si necesitas orientación sobre tratamiento de datos en Costa Rica, consulta los canales oficiales de PRODHAB.'),
    ]),
    'job': dict(label='Oferta de empleo sospechosa', goal='Verificar una oferta y actuar si compartiste información.', sources=[PRIVACY, LAW, PRODHAB], steps=[
        step('Reconocer señales', 'Te ofrecen trabajo sin entrevista. Piden pagar una capacitación y enviar una foto de tu tarjeta hoy.', '¿Qué combinación te hace detenerte?', ['Que el mensaje tenga buena ortografía', 'El pago anticipado y la petición de datos de la tarjeta', 'Que conozcan mi nombre'], 'B', ['La redacción no demuestra la identidad de la empresa.', 'Es una solicitud de alto impacto que necesita verificación independiente.', 'Tu nombre puede haberse obtenido de distintas fuentes.'], 'Detenerte no requiere demostrar un delito: puedes verificar primero.'),
        step('Verificar la oferta', 'El remitente incluye una página y un contacto para confirmar.', '¿Qué haces?', ['Preguntar solo a ese contacto', 'Confiar en sus seguidores', 'Buscar por mi cuenta el canal oficial de la empresa'], 'C', ['El contacto indicado puede ser parte de la misma solicitud.', 'Los seguidores no prueban una relación laboral real.', 'Comprueba que la empresa reconoce la oferta desde un canal independiente.'], 'No envíes documentos ni dinero mientras no hayas comprobado la oferta y sus condiciones.'),
        step('Responder si compartiste datos', 'Imagina que enviaste información de tu tarjeta antes de verificar.', '¿Cuál es la prioridad?', ['Contactar al emisor por su canal oficial y explicar la exposición', 'Esperar unos días', 'Enviar más documentos para cancelar la solicitud'], 'A', ['El emisor puede indicar medidas para proteger la tarjeta y revisar actividad.', 'Esperar mantiene una exposición que puedes comunicar ahora.', 'Enviar más datos puede ampliar el problema.'], 'Las medidas concretas dependen de lo expuesto y de las indicaciones del emisor.'),
        step('Conservar evidencia y buscar apoyo', 'Ya atendiste la exposición de la tarjeta. Quieres saber qué puedes conservar.', '¿Qué eliges?', ['Borrar todos los mensajes', 'Guardar mensajes y comprobantes de forma privada y consultar canales oficiales', 'Publicar documentos del remitente y los míos'], 'B', ['Borrar puede dificultar reconstruir lo ocurrido.', 'Conserva la información y consulta al OIJ si necesitas orientación sobre un posible delito.', 'La publicación puede exponer datos propios y de otras personas.'], 'El asistente no presenta denuncias ni determina que ocurrió un delito.'),
    ]),
}


SIMULATIONS['shopping'] = dict(label='Compra y promoción sospechosa', goal='Verificar una oferta y proteger tus datos al comprar.', sources=[PRIVACY, OIJ], steps=[
    step('Reconocer señales', 'Una tienda anuncia un teléfono muy barato. Exige pagar hoy y enviar una fotografía de tu tarjeta.', '¿Qué te hace detenerte?', ['La presión y la solicitud de la fotografía', 'Que tenga muchas imágenes', 'Que aparezca un candado'], 'A', ['La combinación exige verificar antes de pagar o entregar datos.', 'Las imágenes pueden copiarse.', 'HTTPS no acredita la identidad del comercio.'], 'Todavía puedes detener la compra sin entregar información.'),
    step('Verificar al comercio', 'Quieres confirmar quién vende y cuáles son las condiciones.', '¿Cómo verificas?', ['Solo preguntas al contacto del anuncio', 'Buscas por tu cuenta identidad, contacto oficial y condiciones', 'Confías en comentarios positivos'], 'B', ['El mismo contacto no es una verificación independiente.', 'Comprueba identidad, condiciones y canales de contacto antes de decidir.', 'Los comentarios pueden ser manipulados.'], 'Si no puedes comprobar al vendedor, no continúes.'),
    step('Elegir cómo actuar', 'El comercio sigue sin identificarse y exige el pago.', '¿Qué decisión protege mejor tus datos?', ['Enviar la tarjeta para reservar', 'Pagar una cantidad pequeña para probar', 'Detener la compra y buscar un comercio verificable'], 'C', ['Una fotografía puede exponer datos financieros.', 'Una prueba también puede causar pérdida o exposición.', 'No necesitas completar una operación que no puedes verificar.'], 'Si ya pagaste o compartiste datos financieros, contacta al emisor por su canal oficial.'),
    step('Dar seguimiento', 'Quieres conservar lo ocurrido y evitar nuevas exposiciones.', '¿Qué haces?', ['Guardar evidencia privada y reportar el anuncio', 'Publicar tu tarjeta para advertir', 'Enviar más documentos para cancelar'], 'A', ['Conserva mensajes y comprobantes sin divulgar datos personales.', 'Advertir no requiere publicar información financiera.', 'Entregar más información puede ampliar la exposición.'], 'Para un posible delito consulta los canales oficiales del OIJ; el ejercicio no confirma fraude.')
])
SIMULATIONS['credentials'] = dict(label='Contraseñas y protección del acceso', goal='Proteger cuentas ante reutilización y solicitudes de códigos.', sources=[PRIVACY], steps=[
    step('Reconocer la reutilización', 'Usas la misma contraseña en tu correo y una tienda que anuncia una exposición de credenciales.', '¿Qué debes considerar?', ['Solo importa la tienda', 'La reutilización puede afectar otras cuentas', 'No hay riesgo si la contraseña es larga'], 'B', ['Las mismas credenciales pueden probarse en otros servicios.', 'Protege también las cuentas donde reutilizaste esa credencial.', 'La longitud no elimina el efecto de reutilizar una credencial expuesta.'], 'No significa que todas las cuentas hayan sido comprometidas.'),
    step('Proteger las cuentas', 'Accedes al servicio por su aplicación oficial.', '¿Qué medida eliges?', ['Una contraseña única y verificación en dos pasos', 'La misma contraseña con un número más', 'Enviar tu contraseña al soporte por chat'], 'A', ['Una credencial única reduce el alcance de una exposición; añade verificación en dos pasos.', 'Una variación predecible no ofrece una separación adecuada.', 'No entregues contraseñas a terceros.'], 'Guarda los medios de recuperación de forma segura.'),
    step('Decidir sobre una solicitud', 'Recibes una solicitud de aprobación de acceso que no iniciaste.', '¿Qué haces?', ['Aprobar para que deje de aparecer', 'Compartir el código con quien llama', 'Rechazarla y revisar la actividad desde el servicio oficial'], 'C', ['Aprobar puede autorizar el acceso de otra persona.', 'Un código puede permitir acceso; no lo compartas.', 'No autorices accesos que no iniciaste y revisa la actividad.'], 'Una solicitud inesperada merece revisión, pero por sí sola no confirma una intrusión.'),
    step('Revisar el acceso', 'Quieres comprobar que las medidas siguen activas.', '¿Qué revisas?', ['Solo la foto del perfil', 'Sesiones, medios de recuperación y autenticación', 'Publicar los códigos de recuperación'], 'B', ['La foto no informa sobre sesiones ni autenticación.', 'Revisa accesos y recuperación; utiliza el cierre de sesiones desconocidas que ofrece el proveedor.', 'Los códigos deben conservarse de forma privada.'], 'Si pierdes acceso utiliza la recuperación oficial del proveedor.')
])

def stage_reply(scenario, index, previous=None):
    item = scenario['steps'][index]
    introduction = f"{scenario['label']}\nObjetivo: {scenario['goal']}\n\n" if index == 0 else ''
    recap = f"LO QUE CAMBIÓ\n{previous}\n\n" if previous else ''
    return introduction + recap + f"PASO {index + 1} DE 4 · {item['title'].upper()}\n{item['scene']}\n\nTU DECISIÓN\n{item['question']}"
